name: "Release"

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore --runtime linux-x64 src/
      - name: Build
        run: dotnet build --no-restore --configuration Release --runtime linux-x64 src/
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: src/bin/Release/net8.0/linux-x64/MouseTracker.dll
